def test_success():
    pass


def test_failing():
    raise Exception("It's broken!")
